version: '3.4'

services:
  simplewebapi:
    image: ${DOCKER_REGISTRY-}simplewebapi
    container_name: products.api
    build:
      context: .
      dockerfile: SimpleWebAPI/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"

  products.database:
    image: postgres:latest
    container_name: products.database
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=awizz
      - POSTGRES_PASSWORD=46928146
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  products.cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
